### PR TITLE
Added a basic Express Server to serve the app from the build folder a…

### PR DESCRIPTION
**Pull request by dghalbr**
…nd act as a backend for requests.

### CODE REVIEW

**Comment by neighbor983** [comment]
It doesn't do anything now.

**Comment by dghalbr** [comment]
I'm not sure what's going on. It's not showing express in my package.json, but I see it inside of node_modules. Maybe that's the problem you're having. The reason why I'm not sure is because I have it in my node_modules even though I don't have it declared as a dependency? I'll add it and you should just need to run 'npm install' and then type 'npm run build' and then 'node ./server/server.js' and then navigate to 'localhost:8080' and it should work. I am doing it right now.

**Comment by dghalbr** [comment]
Ok i tried pushing and got errors and when I look at my changes it shows your stuff in there for this pull request. How did you get that into mine? Did you push to this branch?

**Comment by neighbor983** [comment]
Yes i made the changes to your branch and pushed them back up. I made it so when we were ready to push to heroku it would deploy.

**Pull request closed without merging**
